config/routes.rb
Mafalda::Application.routes.draw do
  resources :topicos
  resources :votos

  root :to => "topicos#index"

end

app/models/topico.rb
class Topico < ActiveRecord::Base
  has_many :votos
end

app/models/voto.rb
class Voto < ActiveRecord::Base
  belongs_to :topicos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/topicos_controller.rb
class TopicosController < ApplicationController
  # GET /topicos
  # GET /topicos.xml
  def index
    @topicos = Topico.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topicos }
    end
  end

  # GET /topicos/1
  # GET /topicos/1.xml
  def show
    @topico = Topico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topico }
    end
  end

  # GET /topicos/new
  # GET /topicos/new.xml
  def new
    @topico = Topico.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topico }
    end
  end

  # GET /topicos/1/edit
  def edit
    @topico = Topico.find(params[:id])
  end

  # POST /topicos
  # POST /topicos.xml
  def create
    @topico = Topico.new(params[:topico])

    respond_to do |format|
      if @topico.save
        format.html { redirect_to(root_path, :notice => 'Topico was successfully created.') }
        format.xml  { render :xml => @topico, :status => :created, :location => @topico }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topico.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topicos/1
  # PUT /topicos/1.xml
  def update
    @topico = Topico.find(params[:id])

    respond_to do |format|
      if @topico.update_attributes(params[:topico])
        format.html { redirect_to(@topico, :notice => 'Topico was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topico.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topicos/1
  # DELETE /topicos/1.xml
  def destroy
    @topico = Topico.find(params[:id])
    @topico.destroy

    respond_to do |format|
      format.html { redirect_to(topicos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/votos_controller.rb
class VotosController < ApplicationController
  def create
      topico = Topico.find(params[:topico_id])
      voto   = topico.votos.build

      if voto.save
        flash[:notice] = 'El voto fue creado.'
      else
        flash[:notice] = 'Lo siento. No pudimos contar su voto.'
      end
      redirect_to(topicos_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topicos_helper.rb
module TopicosHelper
end

app/helpers/votos_helper.rb
module VotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mafalda</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="wrapper">
		<header>
			<%= image_tag('mafalda.jpg', :width => '150') %>
		</header>
		<div class="content">
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/topicos/_form.html.erb
<%= form_for(@topico) do |f| %>
  <% if @topico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topico.errors.count, "error") %> prohibited this topico from being saved:</h2>

      <ul>
      <% @topico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topicos/edit.html.erb
<h1>Editing topico</h1>

<%= render 'form' %>

<%= link_to 'Show', @topico %> |
<%= link_to 'Back', topicos_path %>

app/views/topicos/index.html.erb
<h1>Topicos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @topicos.each do |topico| %>
      <tr>
        <td><%= link_to topico.titulo, topico %></td>
        <td></td>
        <td><%= pluralize(topico.votos.length, "voto") %></td>
        <td><%= link_to '+1', votos_path(:topico_id => topico.id), :method => :post %></td>
        <% if topico.votos.empty? %>
            <td><%= link_to 'Edit', edit_topico_path(topico) %></td>
            <td><%= link_to 'Delete', topico, :confirm => 'Are you sure?', :method => :delete %></td>
        <% else %>
        <% end %>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Topico', new_topico_path %>

app/views/topicos/new.html.erb
<h1>New topico</h1>

<%= render 'form' %>

<%= link_to 'Back', topicos_path %>

app/views/topicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @topico.titulo %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @topico.descripcion %>
</p>


<%= link_to 'Edit', edit_topico_path(@topico) %> |
<%= link_to 'Back', topicos_path %>